###############################################################################
# ECS DevEnv Module - ECS Cluster, NLB + Nginx Fargate, DynamoDB Routing, DLP SGs
# Equivalent to cdk/lib/04-ecs-devenv-stack.ts
#
# Architecture: NLB → Nginx (Fargate) → EC2 DevEnv instances
# Nginx config generated by Lambda from DynamoDB routing table
###############################################################################

data "aws_caller_identity" "current" {}
data "aws_region" "current" {}

# ── IAM: ECS Task Role (Bedrock + SSM + CloudWatch) ─────────────────────────

data "aws_iam_policy_document" "ecs_tasks_assume" {
  statement {
    actions = ["sts:AssumeRole"]
    principals {
      type        = "Service"
      identifiers = ["ecs-tasks.amazonaws.com"]
    }
  }
}

resource "aws_iam_role" "ecs_task" {
  name               = "cc-on-bedrock-ecs-task"
  assume_role_policy = data.aws_iam_policy_document.ecs_tasks_assume.json
}

resource "aws_iam_role_policy" "ecs_task_bedrock" {
  name = "bedrock-invoke"
  role = aws_iam_role.ecs_task.id
  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [{
      Effect = "Allow"
      Action = [
        "bedrock:InvokeModel",
        "bedrock:InvokeModelWithResponseStream",
        "bedrock:Converse",
        "bedrock:ConverseStream",
      ]
      Resource = [
        "arn:aws:bedrock:*::foundation-model/anthropic.claude-*",
        "arn:aws:bedrock:*:${data.aws_caller_identity.current.account_id}:inference-profile/global.anthropic.claude-*",
        "arn:aws:bedrock:*:${data.aws_caller_identity.current.account_id}:inference-profile/apac.anthropic.claude-*",
      ]
    }]
  })
}

resource "aws_iam_role_policy" "ecs_task_ssm" {
  name = "ssm-exec"
  role = aws_iam_role.ecs_task.id
  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [{
      Effect = "Allow"
      Action = [
        "ssmmessages:CreateControlChannel",
        "ssmmessages:CreateDataChannel",
        "ssmmessages:OpenControlChannel",
        "ssmmessages:OpenDataChannel",
      ]
      Resource = ["*"]
    }]
  })
}

resource "aws_iam_role_policy" "ecs_task_cloudwatch" {
  name = "cloudwatch-metrics"
  role = aws_iam_role.ecs_task.id
  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [{
      Effect   = "Allow"
      Action   = ["cloudwatch:PutMetricData"]
      Resource = ["*"]
      Condition = {
        StringEquals = { "cloudwatch:namespace" = "CC/DevEnv" }
      }
    }]
  })
}

resource "aws_iam_role_policy" "ecs_task_s3_read" {
  name = "s3-config-read"
  role = aws_iam_role.ecs_task.id
  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [{
      Effect = "Allow"
      Action = ["s3:GetObject", "s3:ListBucket", "s3:HeadObject"]
      Resource = [
        aws_s3_bucket.user_data.arn,
        "${aws_s3_bucket.user_data.arn}/*",
      ]
    }]
  })
}

# ── IAM: ECS Task Execution Role ────────────────────────────────────────────

resource "aws_iam_role" "ecs_task_execution" {
  name               = "cc-on-bedrock-ecs-task-execution"
  assume_role_policy = data.aws_iam_policy_document.ecs_tasks_assume.json
}

resource "aws_iam_role_policy_attachment" "ecs_exec_policy" {
  role       = aws_iam_role.ecs_task_execution.name
  policy_arn = "arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy"
}

resource "aws_iam_role_policy_attachment" "ecs_exec_ecr" {
  role       = aws_iam_role.ecs_task_execution.name
  policy_arn = "arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly"
}

resource "aws_iam_role_policy" "ecs_exec_secrets" {
  name = "secrets-access"
  role = aws_iam_role.ecs_task_execution.id
  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [{
      Effect   = "Allow"
      Action   = ["secretsmanager:GetSecretValue"]
      Resource = "arn:aws:secretsmanager:*:${data.aws_caller_identity.current.account_id}:secret:cc-on-bedrock/*"
    }]
  })
}

# ── ECR Repositories ─────────────────────────────────────────────────────────

resource "aws_ecr_repository" "devenv" {
  name                 = "cc-on-bedrock/devenv"
  image_tag_mutability = "MUTABLE"

  image_scanning_configuration { scan_on_push = true }
  encryption_configuration {
    encryption_type = "KMS"
    kms_key         = var.kms_key_arn
  }
}

resource "aws_ecr_repository" "nginx" {
  name                 = "cc-on-bedrock/nginx"
  image_tag_mutability = "MUTABLE"

  image_scanning_configuration { scan_on_push = true }
  encryption_configuration {
    encryption_type = "KMS"
    kms_key         = var.kms_key_arn
  }
}

# ── S3 Bucket for User Workspace Data ────────────────────────────────────────

resource "aws_s3_bucket" "user_data" {
  bucket = "cc-on-bedrock-user-data-${data.aws_caller_identity.current.account_id}"
  tags   = { Name = "cc-on-bedrock-user-data" }
}

resource "aws_s3_bucket_versioning" "user_data" {
  bucket = aws_s3_bucket.user_data.id
  versioning_configuration { status = "Enabled" }
}

resource "aws_s3_bucket_server_side_encryption_configuration" "user_data" {
  bucket = aws_s3_bucket.user_data.id
  rule {
    apply_server_side_encryption_by_default {
      sse_algorithm     = "aws:kms"
      kms_master_key_id = var.kms_key_arn
    }
  }
}

resource "aws_s3_bucket_lifecycle_configuration" "user_data" {
  bucket = aws_s3_bucket.user_data.id
  rule {
    id     = "noncurrent-cleanup"
    status = "Enabled"
    filter {}
    noncurrent_version_expiration { noncurrent_days = 30 }
  }
}

resource "aws_s3_bucket_public_access_block" "user_data" {
  bucket                  = aws_s3_bucket.user_data.id
  block_public_acls       = true
  block_public_policy     = true
  ignore_public_acls      = true
  restrict_public_buckets = true
}

# ── DLP Security Groups ─────────────────────────────────────────────────────

resource "aws_security_group" "dlp_open" {
  name_prefix = "cc-devenv-open-"
  description = "DLP: Open - all outbound"
  vpc_id      = var.vpc_id

  egress {
    from_port   = 0
    to_port     = 0
    protocol    = "-1"
    cidr_blocks = ["0.0.0.0/0"]
  }

  tags = { Name = "cc-devenv-sg-open" }
}

resource "aws_security_group" "dlp_restricted" {
  name_prefix = "cc-devenv-restricted-"
  description = "DLP: Restricted - whitelist outbound"
  vpc_id      = var.vpc_id

  egress {
    description = "Allow VPC internal"
    from_port   = 0
    to_port     = 0
    protocol    = "-1"
    cidr_blocks = [var.vpc_cidr]
  }

  egress {
    description = "Allow HTTPS for whitelisted domains"
    from_port   = 443
    to_port     = 443
    protocol    = "tcp"
    cidr_blocks = ["0.0.0.0/0"]
  }

  tags = { Name = "cc-devenv-sg-restricted" }
}

resource "aws_security_group" "dlp_locked" {
  name_prefix = "cc-devenv-locked-"
  description = "DLP: Locked - VPC only"
  vpc_id      = var.vpc_id

  egress {
    description = "Allow VPC internal only"
    from_port   = 0
    to_port     = 0
    protocol    = "-1"
    cidr_blocks = [var.vpc_cidr]
  }

  tags = { Name = "cc-devenv-sg-locked" }
}

resource "aws_security_group_rule" "dlp_open_from_nginx" {
  type                     = "ingress"
  from_port                = 8080
  to_port                  = 8080
  protocol                 = "tcp"
  security_group_id        = aws_security_group.dlp_open.id
  source_security_group_id = aws_security_group.nginx.id
  description              = "Allow from Nginx proxy"
}

resource "aws_security_group_rule" "dlp_restricted_from_nginx" {
  type                     = "ingress"
  from_port                = 8080
  to_port                  = 8080
  protocol                 = "tcp"
  security_group_id        = aws_security_group.dlp_restricted.id
  source_security_group_id = aws_security_group.nginx.id
  description              = "Allow from Nginx proxy"
}

resource "aws_security_group_rule" "dlp_locked_from_nginx" {
  type                     = "ingress"
  from_port                = 8080
  to_port                  = 8080
  protocol                 = "tcp"
  security_group_id        = aws_security_group.dlp_locked.id
  source_security_group_id = aws_security_group.nginx.id
  description              = "Allow from Nginx proxy"
}

# ── ECS Cluster ──────────────────────────────────────────────────────────────

resource "aws_ecs_cluster" "this" {
  name = "cc-on-bedrock-devenv"

  setting {
    name  = "containerInsights"
    value = "enabled"
  }
}

# ── ECS Instance Role + Instance Profile ─────────────────────────────────────

data "aws_iam_policy_document" "ec2_assume" {
  statement {
    actions = ["sts:AssumeRole"]
    principals {
      type        = "Service"
      identifiers = ["ec2.amazonaws.com"]
    }
  }
}

resource "aws_iam_role" "ecs_instance" {
  name               = "cc-on-bedrock-ecs-instance"
  assume_role_policy = data.aws_iam_policy_document.ec2_assume.json
}

resource "aws_iam_role_policy_attachment" "ecs_instance_ecs" {
  role       = aws_iam_role.ecs_instance.name
  policy_arn = "arn:aws:iam::aws:policy/service-role/AmazonEC2ContainerServiceforEC2Role"
}

resource "aws_iam_role_policy_attachment" "ecs_instance_ssm" {
  role       = aws_iam_role.ecs_instance.name
  policy_arn = "arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore"
}

resource "aws_iam_instance_profile" "ecs_instance" {
  name = "cc-on-bedrock-ecs-instance"
  role = aws_iam_role.ecs_instance.name
}

# ── ECS Capacity Provider (ASG + Launch Template) ────────────────────────────

data "aws_ssm_parameter" "ecs_arm64_ami" {
  name = "/aws/service/ecs/optimized-ami/amazon-linux-2023/arm64/recommended/image_id"
}

resource "aws_launch_template" "ecs_capacity" {
  name_prefix   = "cc-devenv-ecs-"
  image_id      = data.aws_ssm_parameter.ecs_arm64_ami.value
  instance_type = var.ecs_host_instance_type

  iam_instance_profile {
    arn = aws_iam_instance_profile.ecs_instance.arn
  }

  metadata_options {
    http_endpoint               = "enabled"
    http_tokens                 = "required"
    http_put_response_hop_limit = 1
  }

  block_device_mappings {
    device_name = "/dev/xvda"
    ebs {
      volume_size = 100
      volume_type = "gp3"
      encrypted   = true
    }
  }

  user_data = base64encode(<<-USERDATA
#!/bin/bash
echo "ECS_CLUSTER=${aws_ecs_cluster.this.name}" >> /etc/ecs/ecs.config
echo "ECS_ENABLE_TASK_ENI=true" >> /etc/ecs/ecs.config
echo "ECS_AWSVPC_BLOCK_IMDS=true" >> /etc/ecs/ecs.config
echo "ECS_IMAGE_PULL_BEHAVIOR=always" >> /etc/ecs/ecs.config
USERDATA
  )

  tag_specifications {
    resource_type = "instance"
    tags          = { Name = "cc-devenv-ecs-host" }
  }
}

resource "aws_autoscaling_group" "ecs_capacity" {
  name                  = "cc-devenv-ecs-capacity"
  min_size              = 0
  max_size              = 2
  desired_capacity      = 0
  vpc_zone_identifier   = var.private_subnet_ids
  protect_from_scale_in = false
  termination_policies  = ["OldestInstance"]

  launch_template {
    id      = aws_launch_template.ecs_capacity.id
    version = "$Latest"
  }

  tag {
    key                 = "Name"
    value               = "cc-devenv-ecs-host"
    propagate_at_launch = true
  }

  tag {
    key                 = "AmazonECSManaged"
    value               = "true"
    propagate_at_launch = true
  }
}

resource "aws_ecs_capacity_provider" "this" {
  name = "cc-cp-devenv"

  auto_scaling_group_provider {
    auto_scaling_group_arn         = aws_autoscaling_group.ecs_capacity.arn
    managed_termination_protection = "DISABLED"

    managed_scaling {
      status                    = "ENABLED"
      target_capacity           = 80
      minimum_scaling_step_size = 1
      maximum_scaling_step_size = 10
      instance_warmup_period    = 300
    }
  }
}

resource "aws_ecs_cluster_capacity_providers" "this" {
  cluster_name       = aws_ecs_cluster.this.name
  capacity_providers = [aws_ecs_capacity_provider.this.name]
}

# ── CloudWatch Log Groups ────────────────────────────────────────────────────

resource "aws_cloudwatch_log_group" "devenv" {
  name              = "/cc-on-bedrock/ecs/devenv"
  retention_in_days = 30
}

resource "aws_cloudwatch_log_group" "nginx" {
  name              = "/cc-on-bedrock/ecs/nginx"
  retention_in_days = 14
}

# ── Nginx Security Group ────────────────────────────────────────────────────

resource "aws_security_group" "nginx" {
  name_prefix = "cc-devenv-nginx-"
  description = "Nginx reverse proxy SG"
  vpc_id      = var.vpc_id

  ingress {
    description = "Allow NLB + VPC traffic on port 80"
    from_port   = 80
    to_port     = 80
    protocol    = "tcp"
    cidr_blocks = [var.vpc_cidr]
  }

  egress {
    from_port   = 0
    to_port     = 0
    protocol    = "-1"
    cidr_blocks = ["0.0.0.0/0"]
  }

  tags = { Name = "cc-devenv-nginx-sg" }
}

# ── NLB Security Group ──────────────────────────────────────────────────────

resource "aws_security_group" "nlb" {
  name_prefix = "cc-devenv-nlb-"
  description = "NLB SG - allow CloudFront only"
  vpc_id      = var.vpc_id

  ingress {
    description     = "Allow CloudFront HTTP"
    from_port       = 80
    to_port         = 80
    protocol        = "tcp"
    prefix_list_ids = [var.cloudfront_prefix_list_id]
  }

  egress {
    from_port   = 0
    to_port     = 0
    protocol    = "-1"
    cidr_blocks = ["0.0.0.0/0"]
  }

  tags = { Name = "cc-devenv-nlb-sg" }
}

# ── Network Load Balancer (internet-facing for CloudFront) ───────────────────

resource "aws_lb" "nlb" {
  name               = "cc-devenv-nlb"
  internal           = false
  load_balancer_type = "network"
  security_groups    = [aws_security_group.nlb.id]
  subnets            = var.public_subnet_ids

  enable_cross_zone_load_balancing = true

  tags = { Name = "cc-devenv-nlb" }
}

resource "aws_lb_listener" "nlb" {
  load_balancer_arn = aws_lb.nlb.arn
  port              = 80
  protocol          = "TCP"

  default_action {
    type             = "forward"
    target_group_arn = aws_lb_target_group.nginx.arn
  }
}

resource "aws_lb_target_group" "nginx" {
  name        = "cc-nginx-targets"
  port        = 80
  protocol    = "TCP"
  vpc_id      = var.vpc_id
  target_type = "ip"

  health_check {
    path                = "/health"
    protocol            = "HTTP"
    healthy_threshold   = 2
    unhealthy_threshold = 3
    interval            = 15
  }

  tags = { Name = "cc-nginx-targets" }
}

# ── DynamoDB Routing Table ───────────────────────────────────────────────────

resource "aws_dynamodb_table" "routing" {
  name             = "cc-routing-table"
  billing_mode     = "PAY_PER_REQUEST"
  hash_key         = "subdomain"
  stream_enabled   = true
  stream_view_type = "NEW_AND_OLD_IMAGES"

  attribute {
    name = "subdomain"
    type = "S"
  }

  tags = { Name = "cc-routing-table" }
}

# ── Nginx Config Generator Lambda ────────────────────────────────────────────

data "aws_iam_policy_document" "lambda_assume" {
  statement {
    actions = ["sts:AssumeRole"]
    principals {
      type        = "Service"
      identifiers = ["lambda.amazonaws.com"]
    }
  }
}

resource "aws_iam_role" "nginx_config_lambda" {
  name               = "cc-on-bedrock-nginx-config-gen"
  assume_role_policy = data.aws_iam_policy_document.lambda_assume.json
}

resource "aws_iam_role_policy_attachment" "nginx_config_lambda_basic" {
  role       = aws_iam_role.nginx_config_lambda.name
  policy_arn = "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"
}

resource "aws_iam_role_policy" "nginx_config_lambda_access" {
  name = "dynamodb-s3-access"
  role = aws_iam_role.nginx_config_lambda.id
  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [
      {
        Effect = "Allow"
        Action = [
          "dynamodb:GetItem",
          "dynamodb:Scan",
          "dynamodb:Query",
          "dynamodb:BatchGetItem",
          "dynamodb:DescribeTable",
          "dynamodb:GetRecords",
          "dynamodb:GetShardIterator",
          "dynamodb:DescribeStream",
          "dynamodb:ListStreams",
        ]
        Resource = [
          aws_dynamodb_table.routing.arn,
          "${aws_dynamodb_table.routing.arn}/stream/*",
          "${aws_dynamodb_table.routing.arn}/index/*",
        ]
      },
      {
        Effect   = "Allow"
        Action   = ["s3:PutObject"]
        Resource = ["${aws_s3_bucket.user_data.arn}/*"]
      },
    ]
  })
}

data "archive_file" "nginx_config_lambda" {
  type        = "zip"
  source_file = "${path.module}/../../../cdk/lib/lambda/nginx-config-gen.py"
  output_path = "${path.module}/.build/nginx-config-gen.zip"
}

resource "aws_lambda_function" "nginx_config" {
  function_name    = "cc-on-bedrock-nginx-config-gen"
  role             = aws_iam_role.nginx_config_lambda.arn
  handler          = "nginx-config-gen.handler"
  runtime          = "python3.12"
  timeout          = 30
  filename         = data.archive_file.nginx_config_lambda.output_path
  source_code_hash = data.archive_file.nginx_config_lambda.output_base64sha256

  environment {
    variables = {
      ROUTING_TABLE     = aws_dynamodb_table.routing.name
      CONFIG_BUCKET     = aws_s3_bucket.user_data.id
      CONFIG_KEY        = "nginx/nginx.conf"
      DEV_DOMAIN        = "${var.dev_subdomain}.${var.domain_name}"
      REGION            = data.aws_region.current.name
      CLOUDFRONT_SECRET = var.cloudfront_secret_value
    }
  }
}

resource "aws_lambda_event_source_mapping" "routing_stream" {
  event_source_arn       = aws_dynamodb_table.routing.stream_arn
  function_name          = aws_lambda_function.nginx_config.arn
  starting_position      = "TRIM_HORIZON"
  batch_size             = 10
  maximum_retry_attempts = 3
}

# ── Nginx Task Role (S3 read only — no Bedrock) ─────────────────────────────

resource "aws_iam_role" "nginx_task" {
  name               = "cc-on-bedrock-nginx-task"
  assume_role_policy = data.aws_iam_policy_document.ecs_tasks_assume.json
}

resource "aws_iam_role_policy" "nginx_task_s3" {
  name = "s3-config-read"
  role = aws_iam_role.nginx_task.id
  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [{
      Effect = "Allow"
      Action = ["s3:GetObject", "s3:ListBucket", "s3:HeadObject"]
      Resource = [
        aws_s3_bucket.user_data.arn,
        "${aws_s3_bucket.user_data.arn}/*",
      ]
    }]
  })
}

resource "aws_iam_role_policy" "nginx_task_kms" {
  name = "kms-decrypt"
  role = aws_iam_role.nginx_task.id
  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [{
      Effect   = "Allow"
      Action   = ["kms:Decrypt", "kms:DescribeKey"]
      Resource = [var.kms_key_arn]
    }]
  })
}

# ── Nginx Task Definition (Fargate, ARM64) ───────────────────────────────────

resource "aws_ecs_task_definition" "nginx" {
  family                   = "cc-nginx-proxy"
  requires_compatibilities = ["FARGATE"]
  network_mode             = "awsvpc"
  cpu                      = 256
  memory                   = 512
  task_role_arn            = aws_iam_role.nginx_task.arn
  execution_role_arn       = aws_iam_role.ecs_task_execution.arn

  runtime_platform {
    cpu_architecture        = "ARM64"
    operating_system_family = "LINUX"
  }

  container_definitions = jsonencode([{
    name      = "nginx"
    image     = "${aws_ecr_repository.nginx.repository_url}:latest"
    essential = true

    portMappings = [{ containerPort = 80, protocol = "tcp" }]

    environment = [
      { name = "CONFIG_BUCKET", value = aws_s3_bucket.user_data.id },
      { name = "CONFIG_KEY", value = "nginx/nginx.conf" },
      { name = "RELOAD_INTERVAL", value = "5" },
      { name = "AWS_DEFAULT_REGION", value = data.aws_region.current.name },
      { name = "AWS_REGION", value = data.aws_region.current.name },
    ]

    healthCheck = {
      command     = ["CMD-SHELL", "curl -f http://localhost:80/health || exit 1"]
      interval    = 15
      timeout     = 5
      retries     = 3
      startPeriod = 30
    }

    logConfiguration = {
      logDriver = "awslogs"
      options = {
        "awslogs-group"         = aws_cloudwatch_log_group.nginx.name
        "awslogs-region"        = data.aws_region.current.name
        "awslogs-stream-prefix" = "nginx"
      }
    }
  }])

  tags = { Name = "cc-nginx-proxy" }
}

# ── Nginx ECS Service (Fargate) ──────────────────────────────────────────────

resource "aws_ecs_service" "nginx" {
  name             = "cc-nginx-proxy"
  cluster          = aws_ecs_cluster.this.id
  task_definition  = aws_ecs_task_definition.nginx.arn
  desired_count    = 2
  launch_type      = "FARGATE"
  platform_version = "LATEST"

  enable_execute_command = true

  deployment_minimum_healthy_percent = 50
  deployment_maximum_percent         = 200

  network_configuration {
    subnets          = var.private_subnet_ids
    security_groups  = [aws_security_group.nginx.id]
    assign_public_ip = false
  }

  load_balancer {
    target_group_arn = aws_lb_target_group.nginx.arn
    container_name   = "nginx"
    container_port   = 80
  }

  depends_on = [aws_lb_listener.nlb]
}
