import { NextResponse } from "next/server";

// Force dynamic — must read process.env at request time, not module init time
export const dynamic = "force-dynamic";

// ADR-014 installer endpoint — returns a single self-contained shell script.
// Public (no auth) so users can:
//
//   curl -fsSL https://<dashboard>/api/install | bash
//
// without first visiting the dashboard in a browser. The script:
//   1. Drops cc-bedrock-local into ~/.local/bin (PATH-friendly)
//   2. Writes ~/.config/cc-bedrock/config with COGNITO values baked in here
//   3. Prompts the user to add a `cc()` shell function to ~/.zshrc / ~/.bashrc
//
// COGNITO_CLIENT_ID below is the **public app client** (no secret), see
// CcOnBedrock-Security CliPublicClient. It safely identifies the client in
// public CLI flows; user secrets stay on the user machine.

// NOTE: env values are read inside GET() to avoid Next.js capturing them at
// module init time (standalone build can otherwise embed empty strings).
const CC_FUNCTION = `cc() {
  # Thin wrapper - all logic lives in cc-bedrock-local
  #   cc                       ensure session + run claude (model env from config)
  #   cc --status              show session + limit state
  #   cc --models              show current model config
  #   cc --set-model K=V       change model in config (no zshrc edit needed)
  #   cc --change-email        change Cognito email + re-login
  #   cc --logout              clear cached session
  case "\$1" in
    --status)        cc-bedrock-local status ;;
    --models)        cc-bedrock-local models ;;
    --set-model)     shift; cc-bedrock-local set-model "\$@" ;;
    --change-email)  cc-bedrock-local change-email ;;
    --logout)        cc-bedrock-local logout ;;
    *)               cc-bedrock-local claude "\$@" ;;
  esac
}`;

function installerScript(env: {
  dashboardUrl: string;
  cognitoRegion: string;
  cognitoUserPoolId: string;
  cognitoCliClientId: string;
}) {
  return `#!/usr/bin/env bash
# cc-bedrock-local installer (ADR-014)
# Generated by ${env.dashboardUrl}/api/install at ${new Date().toISOString()}
set -euo pipefail

DASHBOARD_URL="${env.dashboardUrl}"
COGNITO_REGION="${env.cognitoRegion}"
COGNITO_USER_POOL_ID="${env.cognitoUserPoolId}"
COGNITO_CLIENT_ID="${env.cognitoCliClientId}"

CFG_DIR="\${HOME}/.config/cc-bedrock"
BIN_DIR="\${HOME}/.local/bin"
BIN_PATH="\${BIN_DIR}/cc-bedrock-local"

mkdir -p "\${CFG_DIR}" "\${BIN_DIR}"
chmod 700 "\${CFG_DIR}"

echo "[1/4] downloading cc-bedrock-local to \${BIN_PATH}"
curl -fsSL "\${DASHBOARD_URL}/api/install/cli" -o "\${BIN_PATH}"
chmod +x "\${BIN_PATH}"

echo "[2/4] writing config to \${CFG_DIR}/config"
# Email is asked once at install. Stored in config so 'cc' only prompts password
# at runtime. Change later via 'cc-bedrock-local change-email' (or 'cc --change-email').
CC_EMAIL=""
if [[ -e /dev/tty ]]; then
  read -p "  Cognito email: " CC_EMAIL < /dev/tty
fi
cat > "\${CFG_DIR}/config" <<EOF
# cc-bedrock-local config (mode 600). Edit as needed.
# To change models without editing this file directly:
#   cc --set-model opus=global.anthropic.claude-sonnet-4-6
#   cc --set-model fast us.anthropic.claude-haiku-4-5-20251001-v1:0
#   cc --models                         # show current values

DASHBOARD_URL=\${DASHBOARD_URL}
COGNITO_REGION=\${COGNITO_REGION}
COGNITO_USER_POOL_ID=\${COGNITO_USER_POOL_ID}
COGNITO_CLIENT_ID=\${COGNITO_CLIENT_ID}
EMAIL=\${CC_EMAIL}
AWS_PROFILE_NAME=cc-bedrock
AWS_REGION=\${COGNITO_REGION}

# Models (Bedrock inference profile IDs). Default: Sonnet (cheap & fast).
# Switch to Opus anytime:  cc --set-model opus=global.anthropic.claude-opus-4-7
ANTHROPIC_MODEL=global.anthropic.claude-sonnet-4-6
ANTHROPIC_DEFAULT_OPUS_MODEL=global.anthropic.claude-sonnet-4-6
ANTHROPIC_SMALL_FAST_MODEL=us.anthropic.claude-haiku-4-5-20251001-v1:0
CLAUDE_CODE_SUBAGENT_MODEL=global.anthropic.claude-sonnet-4-6
EOF
chmod 600 "\${CFG_DIR}/config"

echo "[3/4] checking PATH"
case ":\${PATH}:" in
  *":\${BIN_DIR}:"*) echo "    \${BIN_DIR} is already on PATH" ;;
  *) echo "    \${BIN_DIR} not in PATH — you may need to add: export PATH=\\"\${BIN_DIR}:\\\$PATH\\"" ;;
esac

# Pick the user shell rc file
SHELL_RC=""
case "\${SHELL:-/bin/bash}" in
  *zsh)  SHELL_RC="\${HOME}/.zshrc" ;;
  *bash) SHELL_RC="\${HOME}/.bashrc" ;;
  *)     SHELL_RC="\${HOME}/.profile" ;;
esac

# Write the cc() function body to a temp file. Avoids the bash 3.2 (macOS default
# /bin/bash) known bug of \$(cat <<EOF ... EOF) heredoc inside command substitution
# parsing incorrectly.
CC_FN_FILE="\$(mktemp /tmp/cc-fn.XXXXXX)"
cat > "\${CC_FN_FILE}" <<'FNEOF'
${CC_FUNCTION}
FNEOF

MARKER_START="# >>> cc-bedrock-local (ADR-014) >>>"
MARKER_END="# <<< cc-bedrock-local (ADR-014) <<<"

echo
echo "[4/4] add 'cc' shell function to \${SHELL_RC}? (y/N)"
if [[ -e /dev/tty ]]; then
  read -r REPLY < /dev/tty
else
  echo "  (no /dev/tty: skipping rc edit; append manually below)"
  REPLY="n"
fi

if [[ "\${REPLY}" =~ ^[Yy] ]]; then
  touch "\${SHELL_RC}"
  if grep -qF "\${MARKER_START}" "\${SHELL_RC}"; then
    # Replace existing block between markers (idempotent install)
    python3 - "\${SHELL_RC}" "\${MARKER_START}" "\${MARKER_END}" "\${CC_FN_FILE}" <<'PYEOF'
import sys, re
path, m_start, m_end, body_file = sys.argv[1], sys.argv[2], sys.argv[3], sys.argv[4]
body = open(body_file).read().rstrip("\\n")
content = open(path).read()
new_block = f"{m_start}\\n{body}\\n{m_end}"
content = re.sub(rf"{re.escape(m_start)}.*?{re.escape(m_end)}", new_block, content, flags=re.S)
open(path, "w").write(content)
PYEOF
    echo "    refreshed cc() block in \${SHELL_RC} (between markers)"
  else
    {
      echo ""
      echo "\${MARKER_START}"
      cat "\${CC_FN_FILE}"
      echo "\${MARKER_END}"
    } >> "\${SHELL_RC}"
    echo "    appended cc() to \${SHELL_RC}"
  fi
  echo
  echo "    Open a new shell (or 'source \${SHELL_RC}') then run:"
  echo "      cc                  # ensure session, launch claude (Bedrock)"
  echo "      cc --change-email   # change Cognito email + re-login"
  echo "      cc --logout         # clear cached session"
else
  echo
  echo "  Skipped \${SHELL_RC} edit. Add the following manually if desired:"
  echo
  echo "\${MARKER_START}"
  cat "\${CC_FN_FILE}"
  echo "\${MARKER_END}"
fi

rm -f "\${CC_FN_FILE}"

echo
echo "Done. First run of 'cc' will prompt for Cognito password (email taken from config)."
echo "  cc                                 # launch claude on Bedrock"
echo "  cc --status                        # session + limit state"
echo "  cc --models                        # show current model config"
echo "  cc --set-model opus=<model-id>     # change a model (no zshrc edit)"
echo "  cc --change-email                  # change Cognito email + re-login"
echo "  cc --logout                        # clear cached refresh token"
`;
}

export async function GET() {
  const script = installerScript({
    dashboardUrl:
      process.env.NEXTAUTH_URL ??
      process.env.DASHBOARD_URL ??
      "https://cconbedrock-dashboard.atomai.click",
    cognitoRegion:
      process.env.COGNITO_REGION ?? process.env.AWS_REGION ?? "ap-northeast-2",
    cognitoUserPoolId: process.env.COGNITO_USER_POOL_ID ?? "",
    cognitoCliClientId: process.env.COGNITO_CLI_CLIENT_ID ?? "",
  });
  return new NextResponse(script, {
    headers: {
      "Content-Type": "text/x-shellscript; charset=utf-8",
      "Cache-Control": "no-store",
    },
  });
}
